### ISSUE TITLE
Add site footer

### ISSUE THREAD

**Issue by ash-lift** [n64blog/n64blog.github.io#47]
The blog needs a footer across all pages.

Suggested content:
- Sitemap link
- Contact link (email?)
- Twitter link
- Facebook link

@megawatts64 Anything else?

**Comment by megawatts64** [comment]
We don't yet have a Facebook page and don't think we need a contact email for the moment. A copyright notice re: written content, while not mandatory, would be nice.

**Comment by ash-lift** [comment]
Some sort of contact link would be useful to have as soon as possible. 

Perhaps the copyright notice for content should live with the article itself and not site-wide? Helps future proof if there is a time when we have guest authors.

**Comment by megawatts64** [comment]
If we must have some way for people to contact us then I would prefer it be a form. I've no use for a form myself at the moment, but understand if you want one so people may contact regarding site design/usability. 

With regard to copyright, my intention was to make it so that guest authors must transfer copyright to me when producing content for the site, but I think that could potentially get messy, as I don't know if an email is sufficient for covering that. A copyright notice is not really required though, as git's terms of service say it belongs to us and copyright is inherent at creation.

With the exception of the link to Twitter, it strikes me that we don't actually need a footer yet because we don't have anything worthwhile to put in it.

**Comment by ash-lift** [comment]
Going to close this as footer is now up, a new issue can be raised for any updates
